### PR TITLE
Fixed everything

### PR DESCRIPTION
**Pull request by kindlehl**

### CODE REVIEW

**Comment by vaughnju** [comment]
That looks like a lot of the changes I have on my local repo too.

**Comment by kindlehl** [comment]
@vaughnju theres only room for one error-fixing PR in this repo

**Comment by vaughnju** [comment]
haha, alright, I won't include my fixes when I push.

**Comment by kindlehl** [comment]
also @vaughnju , can you add the setting to disable merging without a review on a pr

**Comment by wilsconn** [comment]
Great! Removed previous tests that failed to work.

**Pull request merged**
